### ISSUE TITLE
BreizhSR dataset

### ISSUE THREAD

**Issue by robmarkcole** [aimiokab/MISR-S2#1]
Hi
Can you advise if the dataset is online? 
Thanks!

**Comment by danielz02** [comment]
Same question here. Thanks a lot!

**Comment by nshaud** [comment]
Thanks for your interest! We'll update the repo with the dataset, probably before the end of the month.

**Comment by nshaud** [comment]
Done, dataset is available on [Zenodo](https://zenodo.org/records/11551220).
