### ISSUE TITLE
Undefined variables in the "data_gen/preprocess_data.py"

### ISSUE THREAD

**Issue by hubert10** [aimiokab/MISR-S2#4]
Hi Aimi, thanks for providing the code your amazing work.
I have been running into problems when trying to run your codes. Here are two major issues I hope you may have some ideas on how to fix them:

1. The first problem is that the uploaded code contains some undefined variables which make hard to execute the code, to be more precise, the file "data_gen/preprocess_data.py", for example the variable indexes is not defined here https://github.com/aimiokab/MISR-S2/blob/main/data_gen/preprocess_data.py#L61, other variables are easy to fix such as path which should be maybe path_to_dataset here https://github.com/aimiokab/MISR-S2/blob/main/data_gen/preprocess_data.py#L94 etc.

2. When I download the whole datasets, the dataset_train.pkl and dataset_test.pkl files which seem to have beenwere saved with tensorflow, throws some errors when I try to load them with pytorch, the error below is persistent: TypeError: cannot pickle 'tensorflow.python.lib.io._pywrap_file_io.WritableFile' object

Could you please update the code in "data_gen/preprocess_data.py" and let me know if there is chance to sucessfully load these picke files in pytorch ?

I look forward to your positive response.

**Comment by Yassine-Fak** [comment]
Hello, I have the same problems! I created an issue 5 days ago. :)

**Comment by nshaud** [comment]
@hubert10 Could you try preprocessing the data with the new version of the script. You can then check the import of the dataset using:

```python
from utils.dataloader import BreizhSRDataset

ds = BreizhSRDataset("./path/to/the/BreizhSR/dataset/")

print(ds[0])
```

You should get a dictionary with the LR image, the LR image upsampled, the HR image.

**Comment by hubert10** [comment]
@nshaud, yes I tried again a few days ago with the latest version of the code and it works fine. Thank you very much!
